# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Level.create!(rank: "Gaining Control", xp_requirement: 100)
Level.create!(rank: "Gaining Control", xp_requirement: 200)
Level.create!(rank: "Gaining Control", xp_requirement: 300)
Level.create!(rank: "Gaining Control", xp_requirement: 400)
Level.create!(rank: "Gaining Control", xp_requirement: 500)
Level.create!(rank: "Gaining Control", xp_requirement: 600)
Level.create!(rank: "Gaining Control", xp_requirement: 700)
Level.create!(rank: "Gaining Control", xp_requirement: 800)
Level.create!(rank: "Gaining Control", xp_requirement: 900)
Level.create!(rank: "Gaining Control", xp_requirement: 1000)
puts "10 first lvl created"
Level.create!(rank: "Earning Trust", xp_requirement: 1200)
Level.create!(rank: "Earning Trust", xp_requirement: 1400)
Level.create!(rank: "Earning Trust", xp_requirement: 1600)
Level.create!(rank: "Earning Trust", xp_requirement: 1800)
Level.create!(rank: "Earning Trust", xp_requirement: 2000)
Level.create!(rank: "Earning Trust", xp_requirement: 2200)
Level.create!(rank: "Earning Trust", xp_requirement: 2400)
Level.create!(rank: "Earning Trust", xp_requirement: 2600)
Level.create!(rank: "Earning Trust", xp_requirement: 2800)
Level.create!(rank: "Earning Trust", xp_requirement: 3000)
puts "20  lvl created"
Level.create!(rank: "Losing Inhibition", xp_requirement: 4000)
Level.create!(rank: "Losing Inhibition", xp_requirement: 5000)
Level.create!(rank: "Losing Inhibition", xp_requirement: 6000)
Level.create!(rank: "Losing Inhibition", xp_requirement: 7000)
Level.create!(rank: "Losing Inhibition", xp_requirement: 8000)
Level.create!(rank: "Losing Inhibition", xp_requirement: 9000)
Level.create!(rank: "Losing Inhibition", xp_requirement: 11000)
Level.create!(rank: "Losing Inhibition", xp_requirement: 13000)
Level.create!(rank: "Losing Inhibition", xp_requirement: 15000)
Level.create!(rank: "Losing Inhibition", xp_requirement: 17000)
puts "30 lvl created"
Level.create!(rank: "Self esteem", xp_requirement: 20000)
Level.create!(rank: "Self esteem", xp_requirement: 23000)
Level.create!(rank: "Self esteem", xp_requirement: 26000)
Level.create!(rank: "Self esteem", xp_requirement: 29000)
Level.create!(rank: "Self esteem", xp_requirement: 35000)
Level.create!(rank: "Self esteem", xp_requirement: 40000)
Level.create!(rank: "Self esteem", xp_requirement: 45000)
Level.create!(rank: "Self esteem", xp_requirement: 50000)
Level.create!(rank: "Self esteem", xp_requirement: 60000)
Level.create!(rank: "Self esteem", xp_requirement: 70000)
puts "40 lvl created"
